version = 1
SPDX-PackageName = "listening-to"
SPDX-PackageSupplier = "https://github.com/cod3ddot/listening-to"

# configs
[[annotations]]
path = [
    ".gitignore",
    ".gitattributes",
    ".vscode/**/*",
    "bun.lock",
    "package.json",
    "tsconfig.json",
    "biome.jsonc",
]
precedence = "override"
SPDX-FileCopyrightText = "2025 Vsevolod Kutsyn"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["docs/**/*"]
SPDX-FileCopyrightText = "2025 cod3ddot@proton.me"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"
